services:
  init:
    container_name: MariaDB-Init
    build: .
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_ROOT_PASSWORD=secret
      - DB_PORT=3306
      - DB_HOST=MariaDB
    

  db:
    container_name: MariaDB
    image: mariadb:latest
    environment:
      - MARIADB_USER=user1
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=secret
    expose:
      - "3306" 
