services:
  init:
    container_name: MariaDB-Init
    build: .
    environment:
      - DB_USER=root
      - DB_ROOT_PASSWORD=secret
      - DB_PORT=3306
      - DB_HOST=MariaDB
    volumes:
      - shared-volume:/shared
    

  db:
    container_name: MariaDB
    image: mariadb:latest
    environment:
      - MARIADB_USER=user1
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=secret
    expose:
      - "3306" 
    volumes:
      - shared-volume:/tmp
    ports:
      - "13306:3306"

volumes:
  shared-volume: {}
