services:

  db:
    container_name: MariaDB
    image: mariadb:latest
    environment:
      - MARIADB_USER=user1
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=secret
    expose:
      - "3306"
    ports:
      - "3306:3306"
